name: Bug
description: Bug report (MVP Factory standard)
title: "[Bug] "
labels: ["type:bug"]
body:
  - type: input
    id: product
    attributes:
      label: Product
      placeholder: "Amanoba"
    validations:
      required: true

  - type: dropdown
    id: agent
    attributes:
      label: Agent
      options:
        - Chappie
        - Gwen
        - Tribeca
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: Outcome when this bug is fixed.
    validations:
      required: true

  - type: textarea
    id: execution_prompt
    attributes:
      label: Execution Prompt
      description: Explicit instructions an agent can execute immediately.
      placeholder: |
        Implement the bug fix by...
        Update tests for...
    validations:
      required: true

  - type: textarea
    id: scope_non_goals
    attributes:
      label: Scope / Non-goals
      description: What is in scope and explicitly out of scope.
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: Constraints
      description: Safety, platform, policy, or implementation constraints.
    validations:
      required: true

  - type: textarea
    id: acceptance_checks
    attributes:
      label: Acceptance Checks
      description: Checklist of verifiable outcomes.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: textarea
    id: delivery_artifact
    attributes:
      label: Delivery Artifact
      description: Exact expected output (PR/file/report/deploy evidence).
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken, in one sentence.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
    validations:
      required: true

  - type: checkboxes
    id: dod
    attributes:
      label: Definition of Done
      options:
        - label: Root cause identified
          required: true
        - label: Fix implemented and reviewed
          required: true
        - label: Regression risk assessed
          required: true
        - label: Release notes updated (if applicable)
          required: true
