name: Bug
description: Bug report (MVP Factory standard)
title: "[Bug] "
labels: ["type:bug"]
body:
  - type: input
    id: product
    attributes:
      label: Product
      placeholder: "Amanoba"
    validations:
      required: true

  - type: dropdown
    id: agent
    attributes:
      label: Agent
      options:
        - Chappie
        - Tribeca
        - Katja
        - Becca
        - Gwen
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken, in one sentence.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
    validations:
      required: true

  - type: checkboxes
    id: dod
    attributes:
      label: Definition of Done
      options:
        - label: Root cause identified
          required: true
        - label: Fix implemented and reviewed
          required: true
        - label: Regression risk assessed
          required: true
        - label: Release notes updated (if applicable)
          required: true
